server:
  port: 8080

langchain4j:
  open-ai:
    chat-model:
      api-key: ${AI_KEY:}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
      model-name: qwen-plus
#      timeout: 3000
logging:
  level:
    root: