server:
  port: 8080

langchain4j:
  open-ai:
    chat-model:
      api-key: ${API_KEY:}
      base-url:
      log-requests: true
      log-responses: true
      model-name: gpt-4o
      timeout: 3000
